version: '2.0'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      zookeeper:
        aliases:
          - zookeeper

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "pidupdate:1:1,piddelete:1:1,service_events:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    restart: on-failure:1
    networks:
      zookeeper:
      kafka:
        aliases:
          - kafka

  feeder:
    container_name: sitemap-feeder
    build:
      context: .
      dockerfile: ./Dockerfile.sitemapfeeder
    ports:
      - "8081:8081"

networks:
  zookeeper:
  kafka: